# Generated by Django 5.2.8 on 2025-11-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('School', 'School'), ('Work', 'Work'), ('Home', 'Home'), ('Other', 'Other')], default='Other', max_length=6),
        ),
    ]
